[package]
name = "tuckr"
version = "0.3.0"
authors = ["RaphGL"]
edition = "2021"
description = "Super powered GNU Stow replacement"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0.0"
dirs = "4.0.0"
