[package]
name = "tuckr"
version = "0.5.1"
authors = ["RaphGL"]
edition = "2021"
description = "Super powered GNU Stow replacement"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dirs = "4.0"
owo-colors = "3"
tabled = {version = "0.10", features = ["color"]}
